export const RESUME_TEMPLATES = [
  {
    id: 'modern',
    name: 'Modern Tech',
    category: 'Technology & Product',
    badge: 'Popular',
    description: 'Clean two-column layout with accent colors, perfect for software engineers and digital product managers.',
    color: '#1677ff',
  },
  {
    id: 'executive',
    name: 'Executive Sleek',
    category: 'Corporate & Leadership',
    badge: 'Premium',
    description: 'Sophisticated traditional header with strong typographic hierarchy for directors and senior managers.',
    color: '#0f172a',
  },
  {
    id: 'minimalist',
    name: 'Clean Minimalist',
    category: 'Universal & Academic',
    badge: 'ATS Safe',
    description: 'Maximum content density with crisp spacing designed to pass ATS screening algorithms effortlessly.',
    color: '#334155',
  },
  {
    id: 'creative',
    name: 'Creative Sidebar',
    category: 'Design & Marketing',
    badge: 'Creative',
    description: 'Vibrant left sidebar design highlighting profile photo, core competencies, and social links.',
    color: '#7c3aed',
  },
];

export const INITIAL_RESUME_STATE = {
  title: 'Untitled Resume',
  template: 'modern',
  personalInfo: {
    fullName: '',
    jobTitle: '',
    email: '',
    phone: '',
    location: '',
    website: '',
    linkedin: '',
    github: '',
    summary: '',
  },
  skills: [],
  experience: [],
  education: [],
  projects: [],
  certifications: [],
  languages: [],
};

export const SAMPLE_RESUME_DATA = {
  id: 'demo-sample-1',
  title: 'Senior Full Stack Engineer Resume',
  template: 'modern',
  updatedAt: new Date().toISOString(),
  atsScore: 94,
  personalInfo: {
    fullName: 'Alex Vance',
    jobTitle: 'Senior Full Stack Engineer',
    email: 'alex.vance@example.com',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    website: 'https://alexvance.dev',
    linkedin: 'linkedin.com/in/alexvance',
    github: 'github.com/alexvance',
    summary: 'Results-driven Senior Full Stack Engineer with 6+ years of experience designing scalable microservices, cloud-native web applications, and intuitive user interfaces. Expert in React, Node.js, TypeScript, and AWS cloud infrastructures.',
  },
  skills: [
    'React 18',
    'Node.js & Express',
    'TypeScript',
    'GraphQL',
    'PostgreSQL / MongoDB',
    'Docker & Kubernetes',
    'AWS (Lambda, S3, CloudFront)',
    'Ant Design & TailwindCSS',
  ],
  experience: [
    {
      id: 'exp-1',
      company: 'TechCorp Solutions',
      role: 'Senior Full Stack Engineer',
      location: 'San Francisco, CA',
      startDate: '2022-03',
      endDate: 'Present',
      current: true,
      description: 'Architected high-throughput web applications handling 500k+ daily active users. Reduced bundle size by 35% using code splitting and lazy loading. Led a team of 5 engineers in deploying cloud microservices.',
    },
    {
      id: 'exp-2',
      company: 'Innovate Labs',
      role: 'Frontend Engineer',
      location: 'Austin, TX',
      startDate: '2019-06',
      endDate: '2022-02',
      current: false,
      description: 'Built interactive dashboard interfaces using React and Redux Toolkit. Implemented custom data visualization charts using D3.js and automated unit testing suites with Jest.',
    },
  ],
  education: [
    {
      id: 'edu-1',
      institution: 'University of California, Berkeley',
      degree: 'Bachelor of Science in Computer Science',
      startDate: '2015-08',
      endDate: '2019-05',
      gpa: '3.8 / 4.0',
    },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'AI Resume Builder Platform',
      link: 'https://github.com/alexvance/ai-resume-builder',
      description: 'Developed an intelligent web SaaS application enabling users to generate ATS-friendly resumes using AI suggestion algorithms.',
    },
  ],
  certifications: [
    {
      id: 'cert-1',
      title: 'AWS Certified Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      date: '2023-05',
    },
  ],
  languages: ['English (Native)', 'Spanish (Conversational)'],
};
